#!/usr/bin/env bash
#
# install the compiled scripts

DEST="~/Library/Scripts/Applications/"
# this bit of magic does parameter expansion in the DEST variable
DEST="${DEST/#\~/$HOME}"

echo "Installing scripts to $DEST...." >&2
mkdir -p $DEST
cp -rvp script/* "$DEST"
echo "Done." >&2